apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: wiz_cluster_3
  region: us-east-1

nodeGroups:
  - name: nodegroup_1
    instanceType: m5.large
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 20
    ssh:
      allow: true  # Change this based on your preference
