apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: your-existing-cluster-name
  region: your-cluster-region

nodeGroups:
  - name: your-new-nodegroup-name
    instanceType: m5.large
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 20
    ssh:
      allow: true  # Change this based on your preference
