apiVersion: v1
kind: Pod
metadata:
  name: tasky-pod
  labels:
    app: tasky
spec:
  containers:
  - name: tasky-container
    image: automationhoarder9921/tasky:latest
    ports:
    - containerPort: 8080
    env:
    - name: MONGODB_URI
      value: mongodb://192.168.1.25:27017/tasky
    - name: SECRET_KEY
      value: secret12345
---
apiVersion: v1
kind: Service
metadata:
  name: tasky-service
spec:
  type: ClusterIP
  selector:
    app: tasky
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tasky-service
  annotations: # Add this section
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-0fe1822966625131b"
spec:
  type: LoadBalancer
  selector:
    app: tasky
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080