apiVersion: v1
kind: Pod
metadata:
  name: tasky-pod
  labels:
    app: tasky
spec:
  serviceAccountName: tasky
  containers:
  - name: tasky-container
    image: automationhoarder9921/tasky:latest
    ports:
    - containerPort: 8080
    env:
    - name: MONGODB_URI
      value: mongodb://192.168.1.25:27017/tasky
    - name: SECRET_KEY
      value: secret12345
---
apiVersion: v1
kind: Service
metadata:
  name: tasky-cluster-service
spec:
  type: ClusterIP
  selector:
    app: tasky
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tasky-service
  annotations: # Add this section
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-0ed9dd0d9b27e1264"
spec:
  type: LoadBalancer
  selector:
    app: tasky
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tasky-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: User
  name: tasky
  apiGroup: rbac.authorization.k8s.io
